### ISSUE TITLE
 cannot choose a time unit within a day as the ineterval

### ISSUE THREAD

**Issue by EbonexDev** [tradingview/charting-library-examples#318]
![G6kwZs01Ty](https://user-images.githubusercontent.com/107462874/202363724-9720cb5f-65f6-46ed-bcc9-85354d4c8bf6.jpg)

**Comment by serhatopcu** [comment]
Hello,
I will try to answer as far as I know. You can't reach all resolutions because you are getting data by using cryptocompare websocket, you can see this in streaming.js where the line "wss://streamer.cryptocompare.com", you need to pay for all resolutions, but cryptocompare is not only option to get data from, for example i am getting minute resolution data from binance websocket for free. (Let me know if i'm wrong)

**Comment by romfrancois** [comment]
If you refer to this [documentation](https://www.tradingview.com/charting-library-docs/latest/connecting_data/Datafeed-API#onready), this [one](https://www.tradingview.com/charting-library-docs/latest/connecting_data/Datafeed-API#onready) or finally this [one](https://www.tradingview.com/charting-library-docs/latest/ui_elements/Chart/#resolutions-that-are-displayed-in-the-menu) you'll see that there's 2 levels where to define the resolutions. Global ones indicated to the UI and the ones only supported for a given symbol. If some are not available they will be greyed out.
